# Generated by Django 5.2.1 on 2025-06-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_end_date_project_start_date_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_url',
            new_name='github_backend_url',
        ),
        migrations.AddField(
            model_name='project',
            name='github_frontend_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
