# Generated by Django 5.2.1 on 2025-06-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_github_url_project_github_backend_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
