# Generated by Django 5.2.1 on 2025-07-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_experience_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
